#pragma once
#include<iostream>
#include<cstdio>
#include<Windows.h>
using namespace std;

/* UI设计 - 颜色信息 */
//默认色 - 黑底亮白字
const int NONE_COLOR = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY;
//购买时，选中
const int SELECTED_COLOR = BACKGROUND_GREEN | BACKGROUND_BLUE | NONE_COLOR;
//const int SELECTED_COLOR = BACKGROUND_RED | BACKGROUND_GREEN | NONE_COLOR;

//铲除时选中地块
const int REMOVE_COLOR = FOREGROUND_RED | FOREGROUND_INTENSITY;

//植物名字
const int PEASHOOTER_COLOR = BACKGROUND_GREEN | NONE_COLOR;
const int SUNFLOWER_COLOR = BACKGROUND_GREEN | BACKGROUND_RED | NONE_COLOR;
const int CHERRY_BOMB_COLOR = BACKGROUND_RED | NONE_COLOR; 
const int GARLIC_COLOR = 135;
const int SNOW_PEA_COLOR = 155;

//寒冰豌豆
const int SNOW_COLOR = 11;
//减速效果
const int FREEZING_COLOR = 9;
//草地颜色
const int GRASS_COLOR = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
//土地颜色
const int GROUND_COLOR = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN;

//暂停提示
const int PAUSE_COLOR = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN;

const int SUN_AND_SCORE_COLOR = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN;

//冷却时间
const int COOLING = FOREGROUND_RED | FOREGROUND_GREEN;